insert into public.funding (
  type,
  name,
  description,
  provider,
  amount_min,
  amount_max,
  deadline,
  application_url,
  source_url,
  eligibility,
  requirements,
  category,
  tags,
  source,
  status
) values
  (
    'business_grant',
    'Atlantic Growth Grant',
    'Growth funding for Atlantic Canadian small businesses.',
    'Auctus Manual Seed',
    5000,
    25000,
    current_date + interval '45 days',
    'https://example.com/business/atlantic-growth',
    'https://example.com/business/atlantic-growth',
    '{"location":"Atlantic Canada","employees_max":50}'::jsonb,
    array['Operate in Atlantic Canada', 'Have fewer than 50 employees'],
    'Growth',
    array['business','growth','atlantic'],
    'manual',
    'active'
  ),
  (
    'business_grant',
    'Digital Adoption Microgrant',
    'Support for software, ecommerce, and digital operations.',
    'Auctus Manual Seed',
    1000,
    10000,
    current_date + interval '30 days',
    'https://example.com/business/digital-adoption',
    'https://example.com/business/digital-adoption',
    '{"industry":["technology","retail","services"]}'::jsonb,
    array['Submit a digital adoption plan'],
    'Digital',
    array['business','digital'],
    'manual',
    'active'
  ),
  (
    'business_grant',
    'Exporter Readiness Fund',
    'Funding for market expansion outside New Brunswick.',
    'Auctus Manual Seed',
    2500,
    15000,
    null,
    'https://example.com/business/exporter-readiness',
    'https://example.com/business/exporter-readiness',
    '{"province":"NB"}'::jsonb,
    array['New Brunswick business registration'],
    'Export',
    array['business','export'],
    'manual',
    'active'
  ),
  (
    'business_grant',
    'Clean Operations Grant',
    'Support for energy efficiency and cleaner operations.',
    'Auctus Manual Seed',
    5000,
    50000,
    current_date + interval '90 days',
    'https://example.com/business/clean-operations',
    'https://example.com/business/clean-operations',
    '{"project_type":"clean operations"}'::jsonb,
    array['Eligible clean operations project'],
    'Sustainability',
    array['business','sustainability'],
    'manual',
    'active'
  ),
  (
    'business_grant',
    'Startup Validation Grant',
    'Early validation funding for new ventures.',
    'Auctus Manual Seed',
    1000,
    7500,
    current_date + interval '60 days',
    'https://example.com/business/startup-validation',
    'https://example.com/business/startup-validation',
    '{"stage":"startup"}'::jsonb,
    array['Business less than three years old'],
    'Startup',
    array['business','startup'],
    'manual',
    'active'
  ),
  (
    'scholarship',
    'New Brunswick Student Award',
    'Award for students studying at New Brunswick institutions.',
    'Auctus Manual Seed',
    1000,
    5000,
    current_date + interval '50 days',
    'https://example.com/student/nb-award',
    'https://example.com/student/nb-award',
    '{"province":"NB"}'::jsonb,
    array['Enrolled at an eligible institution'],
    'Provincial',
    array['student','nb'],
    'manual',
    'active'
  ),
  (
    'scholarship',
    'STEM Access Scholarship',
    'Scholarship for STEM students.',
    'Auctus Manual Seed',
    2500,
    10000,
    current_date + interval '75 days',
    'https://example.com/student/stem-access',
    'https://example.com/student/stem-access',
    '{"field_of_study":"STEM"}'::jsonb,
    array['Studying in a STEM field'],
    'STEM',
    array['student','stem'],
    'manual',
    'active'
  ),
  (
    'scholarship',
    'Graduate Research Scholarship',
    'Support for masters and doctoral research.',
    'Auctus Manual Seed',
    5000,
    17500,
    current_date + interval '120 days',
    'https://example.com/student/graduate-research',
    'https://example.com/student/graduate-research',
    '{"education_level":["masters","phd"]}'::jsonb,
    array['Graduate enrollment'],
    'Graduate',
    array['student','research'],
    'manual',
    'active'
  ),
  (
    'scholarship',
    'Community Leadership Bursary',
    'Bursary for student leadership and service.',
    'Auctus Manual Seed',
    500,
    3000,
    null,
    'https://example.com/student/community-leadership',
    'https://example.com/student/community-leadership',
    '{"leadership":true}'::jsonb,
    array['Community leadership record'],
    'Leadership',
    array['student','leadership'],
    'manual',
    'active'
  ),
  (
    'scholarship',
    'Applied Trades Scholarship',
    'Scholarship for applied trades programs.',
    'Auctus Manual Seed',
    1000,
    4000,
    current_date + interval '35 days',
    'https://example.com/student/applied-trades',
    'https://example.com/student/applied-trades',
    '{"education_level":"college"}'::jsonb,
    array['Applied trades enrollment'],
    'Trades',
    array['student','trades'],
    'manual',
    'active'
  ),
  (
    'research_grant',
    'Discovery Research Starter Grant',
    'Starter grant for professor-led discovery research.',
    'Auctus Manual Seed',
    10000,
    75000,
    current_date + interval '80 days',
    'https://example.com/research/discovery-starter',
    'https://example.com/research/discovery-starter',
    '{"career_stage":["early","mid"]}'::jsonb,
    array['Professor appointment'],
    'Discovery',
    array['professor','research'],
    'manual',
    'active'
  ),
  (
    'research_grant',
    'Social Innovation Research Fund',
    'Support for applied social innovation research.',
    'Auctus Manual Seed',
    15000,
    100000,
    current_date + interval '95 days',
    'https://example.com/research/social-innovation',
    'https://example.com/research/social-innovation',
    '{"research_area":"social innovation"}'::jsonb,
    array['Institutional approval'],
    'Social Sciences',
    array['professor','ssh','innovation'],
    'manual',
    'active'
  ),
  (
    'research_grant',
    'Industry Partnership Research Grant',
    'Funding for industry-linked research projects.',
    'Auctus Manual Seed',
    25000,
    150000,
    null,
    'https://example.com/research/industry-partnership',
    'https://example.com/research/industry-partnership',
    '{"partner_required":true}'::jsonb,
    array['Industry partner letter'],
    'Partnership',
    array['professor','industry'],
    'manual',
    'active'
  ),
  (
    'research_grant',
    'Equipment Access Grant',
    'Support for research equipment access and shared facilities.',
    'Auctus Manual Seed',
    5000,
    50000,
    current_date + interval '110 days',
    'https://example.com/research/equipment-access',
    'https://example.com/research/equipment-access',
    '{"equipment":true}'::jsonb,
    array['Equipment justification'],
    'Equipment',
    array['professor','equipment'],
    'manual',
    'active'
  ),
  (
    'research_grant',
    'Interdisciplinary Catalyst Grant',
    'Catalyst funding for interdisciplinary teams.',
    'Auctus Manual Seed',
    10000,
    60000,
    current_date + interval '65 days',
    'https://example.com/research/interdisciplinary',
    'https://example.com/research/interdisciplinary',
    '{"team_required":true}'::jsonb,
    array['Two or more disciplines represented'],
    'Interdisciplinary',
    array['professor','team'],
    'manual',
    'active'
  );
